# Generated by Django 5.0.7 on 2025-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='nazwa_uzytkownika',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
