# Generated by Django 5.1.4 on 2025-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sensors",
            "0004_rename_powiadomienie_email_uzytkownik_email_notification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uzytkownik",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="uzytkownik",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
