# Generated by Django 5.1.4 on 2025-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0008_alter_uzytkownik_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="typpomiaru",
            name="jednostka",
            field=models.CharField(default="°C", max_length=50),
            preserve_default=False,
        ),
    ]
