# Generated by Django 5.1.4 on 2025-01-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0010_sensor_zatwierdzony"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="zatwierdzony",
        ),
    ]
