# Generated by Django 5.1.4 on 2025-01-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0011_remove_sensor_zatwierdzony"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request",
            new_name="SensorRequest",
        ),
    ]
