# Generated by Django 5.1.4 on 2025-01-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0014_sensorpermissionrequest_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorrequest",
            name="adres_MAC",
            field=models.CharField(max_length=100),
        ),
    ]
